apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: blue-green-canary
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: quay.io/rhdevelopers/blue-green-canary
          env:
            - name: BLUE_GREEN_CANARY_COLOR
              value: "#5bbf45"
            - name: BLUE_GREEN_CANARY_MESSAGE
              value: "HELLO GREEN"