{
 "title": "Istio Mesh Dashboard",
 "description": "Istio Mesh Dashboard version 1.11.0-beta.2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<div>\n  <div style=\"position: absolute; bottom: 0\">\n    <a href=\"https://istio.io\" target=\"_blank\" style=\"font-size: 30px; text-decoration: none; color: inherit\"><img src=\"https://istio.io/latest/img/istio-bluelogo-nobackground-unframed.svg\" style=\"height: 50px\"> Istio</a>\n  </div>\n  <div style=\"position: absolute; bottom: 0; right: 0; font-size: 15px\">\n    Istio is an <a href=\"https://github.com/istio/istio\" target=\"_blank\">open platform</a> that provides a uniform way to <a href=\"https://istio.io/docs/concepts/security/\" target=\"_blank\">secure</a>,\n    <a href=\"https://istio.io/docs/concepts/traffic-management/\" target=\"_blank\">connect</a>, and \n    <a href=\"https://istio.io/docs/concepts/observability/\" target=\"_blank\">monitor</a> microservices.\n    <br>\n    Need help? <a href=\"https://istio.io/get-involved/\" target=\"_blank\">Join the Istio community</a>.\n  </div>\n</div>"
  },
  {
   "title": "Global Request Volume",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "format": "ops",
   "valueName": "avg",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{reporter=\"source\"}[1m])), 0.001)"
    }
   ]
  },
  {
   "title": "Global Success Rate (non-5xx responses)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "format": "percentunit",
   "valueName": "avg",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{reporter=\"source\", response_code!~\"5.*\"}[1m])) / sum(rate(istio_requests_total{reporter=\"source\"}[1m]))"
    }
   ]
  },
  {
   "title": "4xxs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "format": "ops",
   "valueName": "avg",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"source\", response_code=~\"4.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "5xxs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "format": "ops",
   "valueName": "avg",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"source\", response_code=~\"5.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Virtual Services",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pilot_k8s_cfg_events{type=\"VirtualService\", event=\"add\"}) - (max(pilot_k8s_cfg_events{type=\"VirtualService\", event=\"delete\"}) or max(up * 0))"
    }
   ]
  },
  {
   "title": "Destination Rules",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pilot_k8s_cfg_events{type=\"DestinationRule\", event=\"add\"}) - (max(pilot_k8s_cfg_events{type=\"DestinationRule\", event=\"delete\"}) or max(up * 0))"
    }
   ]
  },
  {
   "title": "Gateways",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pilot_k8s_cfg_events{type=\"Gateway\", event=\"add\"}) - (max(pilot_k8s_cfg_events{type=\"Gateway\", event=\"delete\"}) or max(up * 0))"
    }
   ]
  },
  {
   "title": "Workload Entries",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "format": "none",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pilot_k8s_cfg_events{type=\"WorkloadEntry\", event=\"add\"}) - (max(pilot_k8s_cfg_events{type=\"WorkloadEntry\", event=\"delete\"}) or max(up * 0))"
    }
   ]
  },
  {
   "title": "Service Entries",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pilot_k8s_cfg_events{type=\"ServiceEntry\", event=\"add\"}) - (max(pilot_k8s_cfg_events{type=\"ServiceEntry\", event=\"delete\"}) or max(up * 0))"
    }
   ]
  },
  {
   "title": "PeerAuthentication Policies",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pilot_k8s_cfg_events{type=\"PeerAuthentication\", event=\"add\"}) - (max(pilot_k8s_cfg_events{type=\"PeerAuthentication\", event=\"delete\"}) or max(up * 0))"
    }
   ]
  },
  {
   "title": "RequestAuthentication Policies",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pilot_k8s_cfg_events{type=\"RequestAuthentication\", event=\"add\"}) - (max(pilot_k8s_cfg_events{type=\"RequestAuthentication\", event=\"delete\"}) or max(up * 0))"
    }
   ]
  },
  {
   "title": "Authorization Policies",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "format": "none",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pilot_k8s_cfg_events{type=\"AuthorizationPolicy\", event=\"add\"}) - (max(pilot_k8s_cfg_events{type=\"AuthorizationPolicy\", event=\"delete\"}) or max(up * 0))"
    }
   ]
  },
  {
   "title": "HTTP/GRPC Workloads",
   "type": "table",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "label_join(sum(rate(istio_requests_total{reporter=\"source\", response_code=\"200\"}[1m])) by (destination_workload, destination_workload_namespace, destination_service), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{ destination_workload}}.{{ destination_workload_namespace }}"
    },
    {
     "expr": "label_join((histogram_quantile(0.50, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"source\"}[1m])) by (le, destination_workload, destination_workload_namespace)) / 1000) or histogram_quantile(0.50, sum(rate(istio_request_duration_seconds_bucket{reporter=\"source\"}[1m])) by (le, destination_workload, destination_workload_namespace)), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{ destination_workload}}.{{ destination_workload_namespace }}"
    },
    {
     "expr": "label_join((histogram_quantile(0.90, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"source\"}[1m])) by (le, destination_workload, destination_workload_namespace)) / 1000) or histogram_quantile(0.90, sum(rate(istio_request_duration_seconds_bucket{reporter=\"source\"}[1m])) by (le, destination_workload, destination_workload_namespace)), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}"
    },
    {
     "expr": "label_join((histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"source\"}[1m])) by (le, destination_workload, destination_workload_namespace)) / 1000) or histogram_quantile(0.99, sum(rate(istio_request_duration_seconds_bucket{reporter=\"source\"}[1m])) by (le, destination_workload, destination_workload_namespace)), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}"
    },
    {
     "expr": "label_join((sum(rate(istio_requests_total{reporter=\"source\", response_code!~\"5.*\"}[1m])) by (destination_workload, destination_workload_namespace) / sum(rate(istio_requests_total{reporter=\"source\"}[1m])) by (destination_workload, destination_workload_namespace)), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}"
    }
   ]
  },
  {
   "title": "TCP Workloads",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "label_join(sum(rate(istio_tcp_received_bytes_total{reporter=\"source\"}[1m])) by (destination_workload, destination_workload_namespace, destination_service), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{ destination_workload }}"
    },
    {
     "expr": "label_join(sum(rate(istio_tcp_sent_bytes_total{reporter=\"source\"}[1m])) by (destination_workload, destination_workload_namespace, destination_service), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{ destination_workload }}"
    }
   ]
  },
  {
   "title": "Istio Components by Version",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(istio_build) by (component, tag)",
     "legendFormat": "{{ component }}: {{ tag }}"
    }
   ]
  }
 ]
}