#TODO: Create a full ingress rule
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: metricsingress
  namespace: metrics
spec:
  rules:
    - host: prometheus.local
      http:
        paths:
          - backend:
              serviceName: prometheus-stack-kube-prom-prometheus
              servicePort: 9090