apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: github-client-v8
  namespace: knative-serving
spec:
  template:
  #  metadata:
  #    annotations:
  #      autoscaling.knative.dev/target: "1" # Target 1 in-flight-requests per pod.
    spec:
      containers:
        - image: erasmolpa/github-client:0.0.9
          env:
            - name: TARGET
              value: "Github client"
