apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-go-2
  namespace: knative-serving
spec:
  template:
    spec:
      containers:
      - image: erasmolpa/helloworld-go
        env:
        - name: TARGET
          value: "Go Sample v1"
